### ISSUE TITLE
Support for different expiration policy

### ISSUE THREAD

**Issue by boechat107** [luminus-framework/expiring-map#2]
It would be very useful to support a different [expiration policy](https://github.com/jhalterman/expiringmap#expiration-policies), like `ExpirationPolicy.ACCESSED`.

**Comment by yogthos** [comment]
I guess first thing to figure out is if this will have the desired performance though. :)

**Comment by boechat107** [comment]
OK, I'll do it first in my code to check the performance and then I report you the results.  ;-)

**Comment by yogthos** [comment]
Ok added the expiration policy and listeners, just pushed a new version to clojars. I changed the API slightly so now that a map is passed in for options.

**Comment by yogthos** [comment]
@boechat107 btw I added some benchmarks in tests, if you can think of more feel free to pr :)

**Comment by yogthos** [comment]
So looks like assoc/dissoc cycle is about is about 6 times slower than using a regular atom, which I'd say is pretty acceptable. It might be nice to expose all the options in the memory store. Stuff like listeners could be an interesting addition for the session store.

**Comment by boechat107** [comment]
Ohh, great work, @yogthos!
